name: dct

channels:
  - defaults
  - conda-forge

dependencies:
  # Computing
  - python=3.6  # PSF, https://python.org
  - pip=19  # MIT, https://pip.pypa.io
  - numpy=1.18  # BSD-3, http://numpy.scipy.org
  - scipy=1.2  # BSD-3, http://www.scipy.org
  - pandas=1.0.3  # BSD-3, http://pandas.pydata.org

  # Plotting
  - matplotlib
  - plotly

  - pip:
    - dash==1.18.1
    - dash_bootstrap_components
